### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by schraegregen** [click2install/xumacoin#1]
The script isn't working: "You are not running Ubuntu 16.04. Installation is cancelled."
But for sure, Ubuntu 16.04. ist definitely running on my server!

**Comment by click2install** [comment]
@schraegregen As you will notice the script reports the operating system version from `$(lsb_release -d)`. Can you run `echo $(lsb_release -d)` on your 16.04 instance and present the output here? 

It should be reporting something like `Description: Ubuntu 16.04 LTS`.

**Comment by click2install** [comment]
Pending another instance of this occuring with a better repro, nothing can be done, as numerous other people do not have this issue.
