### ISSUE TITLE
404 not found for XUMA-Linux64-v1.3.0.5.zip file

### ISSUE THREAD

**Issue by sysfu** [click2install/xumacoin#2]
Just tried running the script but it's throwing a 404 not found error for following link: https://github.com/xumacoin/xuma-core/releases/download/v1.3.0.5/XUMA-Linux64-v1.3.0.5.zip

Installation fails shortly afterwards as it cannot cp xumad or xuma-cli.

Environment is Ubuntu 16.04.5 LTS.

**Comment by click2install** [comment]
You can invoke the script with any zip file using the syntax below, provided:
 - it is a full url to the file
 - it is a zip file
```
bash install-xuma.sh <full url to zip file>
```
